[WIP] Implement FITS Tile Compression Library
aperiosoftware/astropy pull request #17
Opened 2022-11-04 12:35 UTC by Cadair

This is an overview PR of all the changes we are making on the `fits-byte-compress-decompress` branch, so we can easily monitor the diff as we work, and get an easier idea of seeing when this needs to be sent upstream.

2022-11-10 14:44 UTC, Cadair commented on astropy/io/fits/tiled_compression/tiled_compression.py
> +        {_GZIP_1_DESCRIPTION}
```suggestion
```

2022-11-29 12:21 UTC, Cadair commented on astropy/io/fits/tiled_compression/src/compression.c
> +  // smaller buffers.
```suggestion
```

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/hdu/compressed.py
> +            # TODO: ZBLANK should not be dealt with here as it should apply
@astrofrog Do we want *to do* this before we open the PR?

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/_codecs.py
> +        {_GZIP_1_DESCRIPTION}
```suggestion
```

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/_codecs.py
> +        # NOTE: we should probably make this less confusing, but nx is shape[0] and ny is shape[1]
What should we do with this?

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/src/compression.c
> +//       uncompressed data, which is safe but too generous.
Looking through the compress wrappers, I think this is actually done?

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/src/compression.c
> +  // TODO: raise an error if bytepix is not 4 or 8
TODO

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/src/compression.c
> +// TODO: add support, if needed, for nullcheck=1
TODO

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/src/compression.c
> +// TODO: add support, if needed, for nullcheck=1
TODO

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/tests/conftest.py
> +        [
```suggestion
        # All compression types can also take quantized floating point input
        [
```

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/tests/test_fitsio.py
> +# skipped on CI, but in all other test runs it's skipped.
```suggestion
# skipped on CI, but in all other test runs it's skipped if fitsio isn't present.
```

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/tests/test_fitsio.py
> +        # ],
```suggestion
```

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/tests/test_fitsio.py
> +        # >3D Data are not currently supported by cfitsio
Do we want to add some round trip tests for things that we support that fitsio dosen't?

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/tests/test_fitsio.py
> +        pytest.xfail("These don't work")
should they??

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/tests/test_fitsio.py
> +        # assert hdul[1].data.dtype.byteorder == np.dtype(dtype).byteorder
Can we restore this somehow?

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/tests/test_fitsio.py
> +    # assert data.dtype.byteorder == np.dtype(dtype).byteorder
same here

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/tiled_compression.py
> +This module contains low level helper functions for compressing and decompressing buffer for the Tiled Table Compression algorithms as specified in the FITS 4 standard.
Line wrap

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/tiled_compression.py
> +
```suggestion
```

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/tiled_compression.py
> +    Drop-in replacement for decompress_hdu from compressionmodule.c
This should probably get a full docstring as it's public API now.

2022-12-15 11:26 UTC, Cadair commented on astropy/io/fits/tiled_compression/tiled_compression.py
> +    Drop-in replacement for compress_hdu from compressionmodule.c
This should probably get a full docstring as it's public API now.

2022-12-15 15:04 UTC, astrofrog commented on astropy/io/fits/hdu/compressed.py
> +            # TODO: ZBLANK should not be dealt with here as it should apply
Yes probably I can take a stab if we have time

2022-12-15 15:05 UTC, astrofrog commented on astropy/io/fits/tiled_compression/_codecs.py
> +        # NOTE: we should probably make this less confusing, but nx is shape[0] and ny is shape[1]
Maybe doesn't matter while private

2022-12-15 15:48 UTC, astrofrog commented on astropy/io/fits/tiled_compression/src/compression.c
> +//       uncompressed data, which is safe but too generous.
Yes done

2022-12-15 15:48 UTC, astrofrog commented on astropy/io/fits/tiled_compression/src/compression.c
> +  // TODO: raise an error if bytepix is not 4 or 8
Yes shouldn't be too hard

2022-12-15 15:51 UTC, astrofrog commented on astropy/io/fits/tiled_compression/src/compression.c
> +// TODO: add support, if needed, for nullcheck=1
Not convinced this is needed as I don't know what functionality it enables. I don't think it is needed before our PR.

2022-12-15 15:51 UTC, astrofrog commented on astropy/io/fits/tiled_compression/src/compression.c
> +// TODO: add support, if needed, for nullcheck=1
As above

2022-12-15 15:52 UTC, astrofrog commented on astropy/io/fits/tiled_compression/tests/test_fitsio.py
> +        # >3D Data are not currently supported by cfitsio
Yes especially if we want to claim we support >3D

2022-12-15 15:52 UTC, astrofrog commented on astropy/io/fits/tiled_compression/tests/test_fitsio.py
> +        pytest.xfail("These don't work")
Probably, maybe they even do pass now?

2022-12-15 15:53 UTC, astrofrog commented on astropy/io/fits/tiled_compression/tests/test_fitsio.py
> +        # assert hdul[1].data.dtype.byteorder == np.dtype(dtype).byteorder
Check if it works currently?

2022-12-15 15:55 UTC, astrofrog commented on astropy/io/fits/tiled_compression/tiled_compression.py
> +    Drop-in replacement for decompress_hdu from compressionmodule.c
Wonder if we can copy in part the docstring of the previous equivalent functions

2022-12-15 16:14 UTC, Cadair commented on astropy/io/fits/tiled_compression/tiled_compression.py
> +    Drop-in replacement for decompress_hdu from compressionmodule.c
did the old functions have docstrings, I can't see them in the c code.

2022-12-16 15:01 UTC, astrofrog requested changes

2023-04-06 15:42 UTC, merged